name: amplify_core
description: The core module for Amplify Flutter.
version: 0.0.1-dev.2
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_core

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  # amplify_core_plugin_interface: ^0.0.1-dev.2
  amplify_core_plugin_interface:
    git:
      url: https://github.com/poached/amplify-flutter.git
      path: packages/amplify_core_plugin_interface
      ref: switch-configuration
  amplify_storage_plugin_interface: ^0.0.1-dev.2
  amplify_analytics_plugin_interface: ^0.0.1-dev.2
  # amplify_auth_plugin_interface: ^0.0.1-dev.2
  amplify_auth_plugin_interface:
    git:
      url: https://github.com/poached/amplify-flutter.git
      path: packages/amplify_auth_plugin_interface
      ref: switch-configuration

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_core
        pluginClass: Core
      ios:
        pluginClass: Core
