name: amplify_auth_cognito
description: The Amplify Flutter Auth category plugin using the AWS Cognito provider.
version: 0.0.1-dev.2
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_auth_cognito

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  # amplify_auth_plugin_interface: ^0.0.1-dev.2
  amplify_auth_plugin_interface:
    git:
      url: https://github.com/poached/amplify-flutter.git
      path: packages/amplify_auth_plugin_interface
      ref: switch-configuration
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # amplify_core: ^0.0.1-dev.2
  amplify_core:
    git:
      url: https://github.com/poached/amplify-flutter.git
      path: packages/amplify_core
      ref: switch-configuration

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_auth_cognito
        pluginClass: AuthCognito
      ios:
        pluginClass: AuthCognito
